name: build-and-deploy-on-push
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: show-payload
        run: |
          git --version
          git clone "https://github.com/KRC00112/zombies.git"
          cd zombies
          echo "npm version: $(npm -v)"
          echo "repo files:"
          npm install
          npm run build
          npm run deploy
          ls -a


