name: build-and-deploy-on-push
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: show-payload
        run: cat "$GITHUB_EVENT_PATH"


