name: build-and-deploy-on-push
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: show-payload
        run: |
          uses:actions/checkout@v3
          ls -a
          git config user.name "KRC00112"
          git config user.email "nylonstripe5u@gmail.com"
          uses: actions/setup-node@v3
          with:
            node-version: '18'
          npm install
          npm run build
          npm run deploy

